package Encapsulamiento;
// Generated 05-20-2015 03:06:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private Integer idBitacora;
     private Usuario usuario;
     private Date hora;
     private Date fecha;
     private String descripcion;

    public Bitacora() {
    }

    public Bitacora(Usuario usuario, Date hora, Date fecha, String descripcion) {
       this.usuario = usuario;
       this.hora = hora;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   
    public Integer getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Integer idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


