package Encapsulamiento;
// Generated 04-15-2015 08:45:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Requerimiento generated by hbm2java
 */
public class Requerimiento  implements java.io.Serializable {


     private String idRequerimiento;
     private Tiporequerimiento tiporequerimiento;
     private String nombre;
     private BigDecimal costo;
     private int horasHombre;
     private String descripcion;
     private Set detallesistemas = new HashSet(0);

    public Requerimiento() {
    }

	
    public Requerimiento(String idRequerimiento, Tiporequerimiento tiporequerimiento, String nombre, BigDecimal costo, int horasHombre, String descripcion) {
        this.idRequerimiento = idRequerimiento;
        this.tiporequerimiento = tiporequerimiento;
        this.nombre = nombre;
        this.costo = costo;
        this.horasHombre = horasHombre;
        this.descripcion = descripcion;
    }
    public Requerimiento(String idRequerimiento, Tiporequerimiento tiporequerimiento, String nombre, BigDecimal costo, int horasHombre, String descripcion, Set detallesistemas) {
       this.idRequerimiento = idRequerimiento;
       this.tiporequerimiento = tiporequerimiento;
       this.nombre = nombre;
       this.costo = costo;
       this.horasHombre = horasHombre;
       this.descripcion = descripcion;
       this.detallesistemas = detallesistemas;
    }
   
    public String getIdRequerimiento() {
        return this.idRequerimiento;
    }
    
    public void setIdRequerimiento(String idRequerimiento) {
        this.idRequerimiento = idRequerimiento;
    }
    public Tiporequerimiento getTiporequerimiento() {
        return this.tiporequerimiento;
    }
    
    public void setTiporequerimiento(Tiporequerimiento tiporequerimiento) {
        this.tiporequerimiento = tiporequerimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public int getHorasHombre() {
        return this.horasHombre;
    }
    
    public void setHorasHombre(int horasHombre) {
        this.horasHombre = horasHombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetallesistemas() {
        return this.detallesistemas;
    }
    
    public void setDetallesistemas(Set detallesistemas) {
        this.detallesistemas = detallesistemas;
    }




}


