package Encapsulamiento;
// Generated 05-20-2015 03:06:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private String idResponsable;
     private Usuario usuario;
     private Set detallesistemas = new HashSet(0);

    public Responsable() {
    }

	
    public Responsable(String idResponsable, Usuario usuario) {
        this.idResponsable = idResponsable;
        this.usuario = usuario;
    }
    public Responsable(String idResponsable, Usuario usuario, Set detallesistemas) {
       this.idResponsable = idResponsable;
       this.usuario = usuario;
       this.detallesistemas = detallesistemas;
    }
   
    public String getIdResponsable() {
        return this.idResponsable;
    }
    
    public void setIdResponsable(String idResponsable) {
        this.idResponsable = idResponsable;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getDetallesistemas() {
        return this.detallesistemas;
    }
    
    public void setDetallesistemas(Set detallesistemas) {
        this.detallesistemas = detallesistemas;
    }




}


