package Encapsulamiento;
// Generated 04-15-2015 08:45:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private String idResponsable;
     private String idUsuario;
     private Set detallesistemas = new HashSet(0);

    public Responsable() {
    }

	
    public Responsable(String idResponsable, String idUsuario) {
        this.idResponsable = idResponsable;
        this.idUsuario = idUsuario;
    }
    public Responsable(String idResponsable, String idUsuario, Set detallesistemas) {
       this.idResponsable = idResponsable;
       this.idUsuario = idUsuario;
       this.detallesistemas = detallesistemas;
    }
   
    public String getIdResponsable() {
        return this.idResponsable;
    }
    
    public void setIdResponsable(String idResponsable) {
        this.idResponsable = idResponsable;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set getDetallesistemas() {
        return this.detallesistemas;
    }
    
    public void setDetallesistemas(Set detallesistemas) {
        this.detallesistemas = detallesistemas;
    }




}


