package Encapsulamiento;
// Generated 05-20-2015 03:06:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private String idTipoUsuario;
     private String descripcion;
     private Set detallepermisos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String idTipoUsuario, String descripcion) {
        this.idTipoUsuario = idTipoUsuario;
        this.descripcion = descripcion;
    }
    public Tipousuario(String idTipoUsuario, String descripcion, Set detallepermisos, Set usuarios) {
       this.idTipoUsuario = idTipoUsuario;
       this.descripcion = descripcion;
       this.detallepermisos = detallepermisos;
       this.usuarios = usuarios;
    }
   
    public String getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(String idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetallepermisos() {
        return this.detallepermisos;
    }
    
    public void setDetallepermisos(Set detallepermisos) {
        this.detallepermisos = detallepermisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


