package Encapsulamiento;
// Generated 05-20-2015 03:06:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private Tipousuario tipousuario;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private byte[] contrasenia;
     private String estado;
     private String correoElectronico;
     private String telefono;
     private Set responsables = new HashSet(0);
     private Set sistemas = new HashSet(0);
     private Set bitacoras = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String idUsuario, Tipousuario tipousuario, String nombre, String apellido1, String apellido2, byte[] contrasenia, String estado, String correoElectronico, String telefono) {
        this.idUsuario = idUsuario;
        this.tipousuario = tipousuario;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.contrasenia = contrasenia;
        this.estado = estado;
        this.correoElectronico = correoElectronico;
        this.telefono = telefono;
    }
    public Usuario(String idUsuario, Tipousuario tipousuario, String nombre, String apellido1, String apellido2, byte[] contrasenia, String estado, String correoElectronico, String telefono, Set responsables, Set sistemas, Set bitacoras) {
       this.idUsuario = idUsuario;
       this.tipousuario = tipousuario;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.contrasenia = contrasenia;
       this.estado = estado;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.responsables = responsables;
       this.sistemas = sistemas;
       this.bitacoras = bitacoras;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public byte[] getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(byte[] contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getResponsables() {
        return this.responsables;
    }
    
    public void setResponsables(Set responsables) {
        this.responsables = responsables;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }




}


